name: AutoPR

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set timestamp as environment variable
        run: echo "TIMESTAMP=$(date '+%s')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update data
        run: echo "${{ env.TIMESTAMP }}" >> auto-pr-test.txt

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c update-data-${{ env.TIMESTAMP }}

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "update-data-${{ env.TIMESTAMP }}"
          commit_message: "update: data"

      - name: Create pull request
        if: steps.auto-commit-action.outputs.changes_detected == false
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "update-data-${{ env.TIMESTAMP }}"
          destination_branch: "main"
          pr_title: "update: テスト"
          github_token: ${{ secrets.GITHUB_TOKEN }}
