name: issue-test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all issues
        id: all_issues
        uses: actions/github-script@v6
        with:
          script: |
            const res = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            console.log(res.data)
