name: issue-test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all issues
        id: all_issues
        uses: actions/github-script@v6
        with:
          script: |
            retuen await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
      - name: show
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.GH_ISSUES)
        env:
          GH_ISSUES: ${{ toJson(steps.all_issues.outputs) }}
