name: issue-test

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  build:
    if: startsWith(github.event.issue.title, '[20')
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all issues
        id: all_issues
        uses: actions/github-script@v6
        with:
          script: |
            return await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
      - name: show
        uses: actions/github-script@v6
        with:
          script: |
            const json = JSON.parse(process.env.GH_ISSUES)
            const j = JSON.parse(json)
            console.log(j.data)
        env:
          GH_ISSUES: ${{ toJson(steps.all_issues.outputs.result) }}
